apiVersion: upgrade.cattle.io/v1
kind: Upgrade
metadata:
  name: kairos-upgrade
spec:
  version: v1.1.0
  upgrade:
    image: 192.168.31.85:5000/kairos-iso:v3.4.2
  nodeSelector:
    matchLabels:
      kairos.io/os: "kairos"
  concurrency: 1
  drain:
    force: true
